const state={movies:[],user:JSON.parse(localStorage.getItem("cinemax_user")||"null"),token:localStorage.getItem("cinemax_token")};
const $=id=>document.getElementById(id);
async function api(url,opt={}){const headers=Object.assign({"Content-Type":"application/json"},opt.headers||{});if(state.token)headers.Authorization="Bearer "+state.token;const r=await fetch(url,Object.assign({},opt,{headers})),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.message||"Request failed");return d}
function renderMovies(ms){state.movies=ms;$("movieGrid").innerHTML=ms.map(m=>'<article class="movie-card"><div class="poster" style="background-image:url(\''+m.poster+'\')"><span class="rating">★ '+m.rating+'</span></div><div class="movie-info"><h3>'+m.title+'</h3><p>'+m.year+' • '+m.genre+'</p><div class="card-actions"><button onclick="showDetails('+m.id+')">Details</button><button class="heart" onclick="toggleFavorite('+m.id+')">♡</button></div></div></article>').join("")||'<p>No movies found.</p>'}
async function loadMovies(){try{renderMovies(await api("/api/movies?search="+encodeURIComponent($("searchInput").value)+"&genre="+encodeURIComponent($("genreFilter").value)))}catch(e){toast(e.message)}}
async function showDetails(id){const m=await api("/api/movies/"+id);$("modalTitle").textContent=m.title;$("modalPoster").style.backgroundImage="url('"+m.backdrop+"')";$("modalMeta").textContent=m.year+" • "+m.genre+" • ★ "+m.rating;$("modalDescription").textContent=m.description;$("favoriteModal").onclick=()=>toggleFavorite(m.id);$("movieModal").classList.add("open")}
async function toggleFavorite(id){if(!state.token)return openAuth("login");try{const f=await api("/api/favorites"),exists=f.some(x=>x.id===id);await api("/api/favorites/"+id,{method:exists?"DELETE":"POST"});toast(exists?"Removed from favorites":"Added to favorites")}catch(e){toast(e.message)}}
function openAuth(mode){$("authModal").classList.add("open");$("authForm").dataset.mode=mode;$("authTitle").textContent=mode==="login"?"Welcome Back":"Create Account";$("authSubmit").textContent=mode==="login"?"Login":"Sign Up";$("name").style.display=mode==="login"?"none":"block"}
$("authForm").addEventListener("submit",async e=>{e.preventDefault();const mode=e.currentTarget.dataset.mode,body={email:$("email").value,password:$("password").value};if(mode==="register")body.name=$("name").value;try{const d=await api("/api/auth/"+mode,{method:"POST",body:JSON.stringify(body)});state.token=d.token;state.user=d.user;localStorage.setItem("cinemax_token",d.token);localStorage.setItem("cinemax_user",JSON.stringify(d.user));$("authModal").classList.remove("open");updateUser();toast("Success")}catch(e){toast(e.message)}});
function updateUser(){$("userButton").textContent=state.user?"Hi, "+state.user.name.split(" ")[0]:"Login"}
function logout(){state.user=null;state.token=null;localStorage.removeItem("cinemax_user");localStorage.removeItem("cinemax_token");updateUser();toast("Logged out")}
function toast(msg){$("toast").textContent=msg;$("toast").classList.add("show");setTimeout(()=>$("toast").classList.remove("show"),2500)}
$("searchInput").addEventListener("input",loadMovies);$("genreFilter").addEventListener("change",loadMovies);$("userButton").onclick=()=>state.user?logout():openAuth("login");$("signupButton").onclick=()=>openAuth("register");window.showDetails=showDetails;window.toggleFavorite=toggleFavorite;window.openAuth=openAuth;window.closeModal=()=>document.querySelectorAll(".modal").forEach(x=>x.classList.remove("open"));loadMovies();updateUser();
