const state={token:localStorage.getItem("cinemax_token"),user:JSON.parse(localStorage.getItem("cinemax_user")||"null")};const $=id=>document.getElementById(id);
async function api(u,o={}){const h={"Content-Type":"application/json",...(o.headers||{})};if(state.token)h.Authorization="Bearer "+state.token;const r=await fetch(u,{...o,headers:h}),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.message||"Request failed");return d}
function toast(x){$("toast").textContent=x;$("toast").classList.add("show");setTimeout(()=>$("toast").classList.remove("show"),2200)}
function render(ms){$("movieGrid").innerHTML=ms.map(m=>`<article class="movie-card"><div class="poster" style="background-image:url('${m.poster}')"><b>★ ${m.rating}</b></div><div class="movie-info"><h3>${m.title}</h3><p>${m.year} • ${m.genre}</p><button onclick="location.href='movie.html?id=${m.id}'">View Movie</button><button onclick="fav(${m.id})">♡</button></div></article>`).join("")}
async function load(){const q=new URLSearchParams({search:$("searchInput").value,genre:$("genreFilter").value});render(await api("/api/movies?"+q))}
async function fav(id){if(!state.token)return openAuth("login");await api("/api/favorites/"+id,{method:"POST"});toast("Added to watchlist")}
function openAuth(mode){$("authModal").classList.add("open");$("authForm").dataset.mode=mode;$("authTitle").textContent=mode==="login"?"Login":"Create Account";$("name").style.display=mode==="login"?"none":"block"}
$("authForm").onsubmit=async e=>{e.preventDefault();const mode=e.currentTarget.dataset.mode,b={email:$("email").value,password:$("password").value};if(mode==="register")b.name=$("name").value;try{const d=await api("/api/auth/"+mode,{method:"POST",body:JSON.stringify(b)});state.token=d.token;state.user=d.user;localStorage.setItem("cinemax_token",d.token);localStorage.setItem("cinemax_user",JSON.stringify(d.user));$("authModal").classList.remove("open");update();toast("Welcome to CineMax")}catch(x){toast(x.message)}}
function update(){if(state.user){$("userButton").textContent="Hi, "+state.user.name.split(" ")[0];$("profileLink").style.display="inline";$("watchLink").style.display="inline";if(state.user.role==="admin")$("adminLink").style.display="inline"}}
$("searchInput").oninput=load;$("genreFilter").onchange=load;$("userButton").onclick=()=>state.user?location.href="profile.html":openAuth("login");$("signupButton").onclick=()=>openAuth("register");window.openAuth=openAuth;window.fav=fav;update();load();