require("dotenv").config();
const path=require("path"),express=require("express"),cors=require("cors"),bcrypt=require("bcryptjs"),jwt=require("jsonwebtoken"),Database=require("better-sqlite3");
const app=express(),PORT=process.env.PORT||3000,SECRET=process.env.JWT_SECRET||"change-this-secret";
const db=new Database("cinemax.db"); app.use(cors());app.use(express.json());app.use(express.static(__dirname));
db.exec(`CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,email TEXT UNIQUE NOT NULL,password TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'user',avatar TEXT DEFAULT '',bio TEXT DEFAULT '',created_at DATETIME DEFAULT CURRENT_TIMESTAMP);CREATE TABLE IF NOT EXISTS favorites(user_id INTEGER NOT NULL,movie_id INTEGER NOT NULL,PRIMARY KEY(user_id,movie_id));CREATE TABLE IF NOT EXISTS movies(id INTEGER PRIMARY KEY,title TEXT NOT NULL,year INTEGER NOT NULL,genre TEXT NOT NULL,rating REAL NOT NULL,poster TEXT NOT NULL,backdrop TEXT NOT NULL,description TEXT NOT NULL,video_url TEXT DEFAULT '',featured INTEGER DEFAULT 0);`);
const seed=[["Avengers: Endgame",2019,"Action",9,"https://images.unsplash.com/photo-1531259683007-016a7b628fc3?auto=format&fit=crop&w=700&q=80","https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1600&q=80","The Avengers unite for their final battle to restore what was lost."],["Spider-Man",2021,"Action",8.7,"https://images.unsplash.com/photo-1635805737707-575885ab0820?auto=format&fit=crop&w=700&q=80","https://images.unsplash.com/photo-1534801022020-3c9c5c0a0c0d?auto=format&fit=crop&w=1600&q=80","A young hero learns that great power comes with great responsibility."],["The Batman",2022,"Drama",8.5,"https://images.unsplash.com/photo-1509347528160-9a9e33742cdb?auto=format&fit=crop&w=700&q=80","https://images.unsplash.com/photo-1519638399535-1b036603ac77?auto=format&fit=crop&w=1600&q=80","Batman investigates a dangerous mystery hidden beneath Gotham City."],["Interstellar",2014,"Sci-Fi",9.1,"https://images.unsplash.com/photo-1462331940025-496dfbfc7564?auto=format&fit=crop&w=700&q=80","https://images.unsplash.com/photo-1446776877081-d282a0f896e2?auto=format&fit=crop&w=1600&q=80","Explorers travel beyond our solar system in search of a future for humanity."],["John Wick",2014,"Action",8.4,"https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=700&q=80","https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=1600&q=80","A legendary action thriller about a retired assassin pulled back into danger."],["Avatar",2009,"Sci-Fi",8.8,"https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=700&q=80","https://images.unsplash.com/photo-1534791547706-9f67f1b2c8c0?auto=format&fit=crop&w=1600&q=80","A marine discovers a new world and becomes caught between two civilizations."]];
const add=db.prepare("INSERT OR IGNORE INTO movies(title,year,genre,rating,poster,backdrop,description) VALUES(?,?,?,?,?,?,?)");seed.forEach(m=>add.run(...m));
function auth(req,res,next){const t=(req.headers.authorization||"").replace("Bearer ","");if(!t)return res.status(401).json({message:"Login required"});try{req.user=jwt.verify(t,SECRET);next()}catch(e){res.status(401).json({message:"Invalid token"})}}
function admin(req,res,next){if(req.user.role!=="admin")return res.status(403).json({message:"Admin access required"});next()}
app.get("/api/health",(q,s)=>s.json({status:"ok"}));
app.get("/api/movies",(req,res)=>{let sql="SELECT * FROM movies WHERE 1=1",p={};if(req.query.search){sql+=" AND title LIKE @search";p.search="%"+req.query.search+"%"}if(req.query.genre&&req.query.genre!=="all"){sql+=" AND genre=@genre";p.genre=req.query.genre}sql+=" ORDER BY featured DESC,rating DESC";res.json(db.prepare(sql).all(p))});
app.get("/api/movies/:id",(req,res)=>{const m=db.prepare("SELECT * FROM movies WHERE id=?").get(req.params.id);m?res.json(m):res.status(404).json({message:"Movie not found"})});
app.post("/api/auth/register",async(req,res)=>{const{name,email,password}=req.body;if(!name||!email||!password||password.length<6)return res.status(400).json({message:"Complete all fields; password must be 6+ characters"});try{const r=db.prepare("INSERT INTO users(name,email,password) VALUES(?,?,?)").run(name,email.toLowerCase(),await bcrypt.hash(password,12));const u={id:Number(r.lastInsertRowid),name,email:email.toLowerCase(),role:"user"};res.status(201).json({token:jwt.sign(u,SECRET,{expiresIn:"7d"}),user:u})}catch(e){res.status(409).json({message:"Email already registered"})}});
app.post("/api/auth/login",async(req,res)=>{const u=db.prepare("SELECT * FROM users WHERE email=?").get((req.body.email||"").toLowerCase());if(!u||!(await bcrypt.compare(req.body.password||"",u.password)))return res.status(401).json({message:"Invalid email or password"});const safe={id:u.id,name:u.name,email:u.email,role:u.role,avatar:u.avatar,bio:u.bio};res.json({token:jwt.sign(safe,SECRET,{expiresIn:"7d"}),user:safe})});
app.get("/api/me",auth,(req,res)=>res.json(db.prepare("SELECT id,name,email,role,avatar,bio,created_at FROM users WHERE id=?").get(req.user.id)));
app.put("/api/profile",auth,(req,res)=>{const{name,avatar,bio}=req.body;db.prepare("UPDATE users SET name=COALESCE(?,name),avatar=COALESCE(?,avatar),bio=COALESCE(?,bio) WHERE id=?").run(name,avatar,bio,req.user.id);res.json({message:"Profile updated"})});
app.get("/api/favorites",auth,(req,res)=>res.json(db.prepare("SELECT movies.* FROM movies JOIN favorites ON movies.id=favorites.movie_id WHERE favorites.user_id=? ORDER BY movies.rating DESC").all(req.user.id)));
app.post("/api/favorites/:id",auth,(req,res)=>{db.prepare("INSERT OR IGNORE INTO favorites VALUES(?,?)").run(req.user.id,req.params.id);res.json({message:"Added to watchlist"})});
app.delete("/api/favorites/:id",auth,(req,res)=>{db.prepare("DELETE FROM favorites WHERE user_id=? AND movie_id=?").run(req.user.id,req.params.id);res.json({message:"Removed from watchlist"})});
app.get("/api/admin/stats",auth,admin,(req,res)=>res.json({users:db.prepare("SELECT COUNT(*) c FROM users").get().c,movies:db.prepare("SELECT COUNT(*) c FROM movies").get().c,watchlist:db.prepare("SELECT COUNT(*) c FROM favorites").get().c}));
app.get("/api/admin/users",auth,admin,(req,res)=>res.json(db.prepare("SELECT id,name,email,role,created_at FROM users ORDER BY id DESC").all()));
app.post("/api/admin/movies",auth,admin,(req,res)=>{const m=req.body,r=db.prepare("INSERT INTO movies(title,year,genre,rating,poster,backdrop,description,video_url,featured) VALUES(?,?,?,?,?,?,?,?,?)").run(m.title,m.year,m.genre,m.rating,m.poster,m.backdrop,m.description,m.video_url||"",m.featured?1:0);res.status(201).json({id:Number(r.lastInsertRowid)})});
app.put("/api/admin/movies/:id",auth,admin,(req,res)=>{const m=req.body;db.prepare("UPDATE movies SET title=?,year=?,genre=?,rating=?,poster=?,backdrop=?,description=?,video_url=?,featured=? WHERE id=?").run(m.title,m.year,m.genre,m.rating,m.poster,m.backdrop,m.description,m.video_url||"",m.featured?1:0,req.params.id);res.json({message:"Movie updated"})});
app.delete("/api/admin/movies/:id",auth,admin,(req,res)=>{db.prepare("DELETE FROM movies WHERE id=?").run(req.params.id);res.json({message:"Movie deleted"})});
app.get("*",(req,res)=>res.sendFile(path.join(__dirname,"index.html")));app.listen(PORT,()=>console.log("CineMax running on http://localhost:"+PORT));