require("dotenv").config();
const path=require("path"), express=require("express"), cors=require("cors"), bcrypt=require("bcryptjs"), jwt=require("jsonwebtoken"), Database=require("better-sqlite3");
const app=express(), PORT=process.env.PORT||3000, JWT_SECRET=process.env.JWT_SECRET||"change-this-secret-in-production", db=new Database("cinemax.db");
app.use(cors()); app.use(express.json()); app.use(express.static(__dirname));
db.exec("CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,email TEXT UNIQUE NOT NULL,password TEXT NOT NULL,created_at DATETIME DEFAULT CURRENT_TIMESTAMP); CREATE TABLE IF NOT EXISTS favorites(user_id INTEGER NOT NULL,movie_id INTEGER NOT NULL,PRIMARY KEY(user_id,movie_id)); CREATE TABLE IF NOT EXISTS movies(id INTEGER PRIMARY KEY,title TEXT NOT NULL,year INTEGER NOT NULL,genre TEXT NOT NULL,rating REAL NOT NULL,poster TEXT NOT NULL,backdrop TEXT NOT NULL,description TEXT NOT NULL);");
const movies=[
[1,"Avengers: Endgame",2019,"Action",9.0,"https://images.unsplash.com/photo-1531259683007-016a7b628fc3?auto=format&fit=crop&w=700&q=80","https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1600&q=80","The Avengers unite for their final battle to restore what was lost."],
[2,"Spider-Man",2021,"Action",8.7,"https://images.unsplash.com/photo-1635805737707-575885ab0820?auto=format&fit=crop&w=700&q=80","https://images.unsplash.com/photo-1534801022020-3c9c5c0a0c0d?auto=format&fit=crop&w=1600&q=80","A young hero learns that great power comes with great responsibility."],
[3,"The Batman",2022,"Drama",8.5,"https://images.unsplash.com/photo-1509347528160-9a9e33742cdb?auto=format&fit=crop&w=700&q=80","https://images.unsplash.com/photo-1519638399535-1b036603ac77?auto=format&fit=crop&w=1600&q=80","Batman investigates a dangerous mystery hidden beneath Gotham City."],
[4,"Interstellar",2014,"Sci-Fi",9.1,"https://images.unsplash.com/photo-1462331940025-496dfbfc7564?auto=format&fit=crop&w=700&q=80","https://images.unsplash.com/photo-1446776877081-d282a0f896e2?auto=format&fit=crop&w=1600&q=80","Explorers travel beyond our solar system in search of a future for humanity."],
[5,"John Wick",2014,"Action",8.4,"https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=700&q=80","https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=1600&q=80","A legendary action thriller about a retired assassin pulled back into danger."],
[6,"Avatar",2009,"Sci-Fi",8.8,"https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=700&q=80","https://images.unsplash.com/photo-1534791547706-9f67f1b2c8c0?auto=format&fit=crop&w=1600&q=80","A marine discovers a new world and becomes caught between two civilizations."]
];
const add=db.prepare("INSERT OR IGNORE INTO movies VALUES(?,?,?,?,?,?,?,?)"); movies.forEach(m=>add.run(...m));
function auth(req,res,next){const h=req.headers.authorization||"",t=h.startsWith("Bearer ")?h.slice(7):null;if(!t)return res.status(401).json({message:"Authentication required"});try{req.user=jwt.verify(t,JWT_SECRET);next()}catch(e){res.status(401).json({message:"Invalid or expired token"})}}
app.get("/api/health",(req,res)=>res.json({status:"ok",service:"CineMax API"}));
app.get("/api/movies",(req,res)=>{const search=req.query.search||"",genre=req.query.genre||"",limit=Math.min(Number(req.query.limit)||50,100);let sql="SELECT * FROM movies WHERE 1=1",p={limit};if(search){sql+=" AND (title LIKE @search OR description LIKE @search)";p.search="%"+search+"%"}if(genre&&genre!=="all"){sql+=" AND genre=@genre";p.genre=genre}sql+=" ORDER BY rating DESC LIMIT @limit";res.json(db.prepare(sql).all(p))});
app.get("/api/movies/:id",(req,res)=>{const m=db.prepare("SELECT * FROM movies WHERE id=?").get(req.params.id);m?res.json(m):res.status(404).json({message:"Movie not found"})});
app.post("/api/auth/register",async(req,res)=>{const {name,email,password}=req.body;if(!name||!email||!password||password.length<6)return res.status(400).json({message:"Name, email and a password of at least 6 characters are required"});try{const hash=await bcrypt.hash(password,12),r=db.prepare("INSERT INTO users(name,email,password) VALUES(?,?,?)").run(name,email.toLowerCase(),hash),u={id:Number(r.lastInsertRowid),name,email:email.toLowerCase()};res.status(201).json({token:jwt.sign(u,JWT_SECRET,{expiresIn:"7d"}),user:u})}catch(e){res.status(409).json({message:"An account with that email already exists"})}});
app.post("/api/auth/login",async(req,res)=>{const u=db.prepare("SELECT * FROM users WHERE email=?").get((req.body.email||"").toLowerCase());if(!u||!(await bcrypt.compare(req.body.password||"",u.password)))return res.status(401).json({message:"Invalid email or password"});const safe={id:u.id,name:u.name,email:u.email};res.json({token:jwt.sign(safe,JWT_SECRET,{expiresIn:"7d"}),user:safe})});
app.get("/api/me",auth,(req,res)=>res.json(req.user));
app.get("/api/favorites",auth,(req,res)=>res.json(db.prepare("SELECT movies.* FROM movies JOIN favorites ON favorites.movie_id=movies.id WHERE favorites.user_id=? ORDER BY movies.rating DESC").all(req.user.id)));
app.post("/api/favorites/:id",auth,(req,res)=>{db.prepare("INSERT OR IGNORE INTO favorites(user_id,movie_id) VALUES(?,?)").run(req.user.id,req.params.id);res.json({message:"Added to favorites"})});
app.delete("/api/favorites/:id",auth,(req,res)=>{db.prepare("DELETE FROM favorites WHERE user_id=? AND movie_id=?").run(req.user.id,req.params.id);res.json({message:"Removed from favorites"})});
app.get("*",(req,res)=>res.sendFile(path.join(__dirname,"index.html")));
app.listen(PORT,()=>console.log("CineMax running on http://localhost:"+PORT));
